LoadPackage("NumericalSgps");
#
# computes the numerical semigroup generated by
# all primes between a prime p and 2*p
# shows the tendency of the quotient f/p to be 4
#
primes := Filtered([2..10000],IsPrime);

for p in primes do
    
    ng := NumericalSemigroup(Filtered([p..2*p],IsPrime));

    e := EmbeddingDimension(ng);

    m:= Multiplicity(ng);

    f := FrobeniusNumber(ng);

    Print("e=",e,"   m=",m,"    f=",f,"   f/m=",1.0*f/m,"\n");
od;

